export const footerTitleES = 'Shield.js'
export const oneBeyondSubtitleES = 'Desde 2023 - One Beyond'
export const contactUsTitleES = 'Contacta con nosotros'
export const footerTitleEN = 'Shield.js'
export const oneBeyondSubtitleEN = 'Since 2023 - One Beyond'
export const contactUsTitleEN = 'Contact us'
